### ISSUE TITLE
Installation fails check on Red Hat 6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#104]
```
What steps will reproduce the problem?
1. Unpack from tar.gz
2. ./configure --prefix==<current dir>
3. make
4. make install
5. make check

What is the expected output? What do you see instead?
Expected: Pass all tests
Observed:
....
Running HashtableAllTest.Equals.18
Running HashtableTest.IntIO
Test failed: fp != NULL
FAIL: hashtable_test
PASS
PASS: simple_test
PASS
PASS: simple_compat_test
===================================================
1 of 7 tests failed
Please report to google-sparsehash@googlegroups.com
===================================================

What version of the product are you using? On what operating system?
v2.0.2 on RHEL 6

Please provide any additional information below.


```

Original issue reported on code.google.com by `cgan...@gmail.com` on 22 Sep 2014 at 5:41

**Comment by Dekken** [comment]
Comment if it comes up again. Can't test RHEL, but Debian is ok with GCC 5.3 and version 2.0.3.

**Comment by cswarth** [comment]
This issue can still be triggered today, and it's maddening when it occurs.  The problem is the  [TmpFile](https://github.com/sparsehash/sparsehash/blob/master/src/hashtable_test.cc#L103) function in hashtable_test.cc.   The author was apparently uninformed about how temp files are supposed to work on multi-user systems.  This should be replaced with a call to `tmpnam_r()` or even better, ` tmpfile (void)` to avoid this installation error.

The problems are 
1) don't assume that temp files are created under /tmp! 
2) don't create predictable temporary file names!
3) remove your temp files!

When the first user runs `hashtable_test`, it leaves a temp file named  "/tmp/intio".   Maybe it succeeds, maybe it fails - in either case `hashtable_test` leaves the temp file around.
Now another user tries to compile the package, and when they get to `hashtable_test` it fails because there is already a temp file named `/tmp/intio` and it is owner by somebody else!
The failure to open the temp file is flagged as a failure of the sparse hash package, which seems like another bug too.

**Comment by donovanhide** [comment]
Thanks for raising this. Bear in mind that sparsehash was perhaps written before the C++ standard library had a tmpfile function:

http://en.cppreference.com/w/cpp/io/c/tmpfile

This problem is solved in the C++11 version. If you want to backport the changes to this version, patches are welcome, although I don't know the ins and outs of autoconf checking for the existence of tmpfile in the standard library.

https://github.com/sparsehash/sparsehash-c11/blob/3eda9ea2da8c91adaf052500220d14efec263bbc/tests/hashtable_unittests.cc#L1398

Alternatively, you could just look at using the C++11 version :-)

**Comment by cswarth** [comment]
I've patched a local version of hashtest, but do you think it worth making a PR to address the tmpfile issue?  Or is the C++11 version the one that should be getting attention now?  I'm not sure of what's in the compatibility matrix for the projects so I don't know what assumptions I can make about the build environment.

I ran into this because sparsehash release version is an automatic dependency of another package (`graph-tool`), installed via `lunixbrew`, so using the c++11 version wasn't an option.

**Comment by donovanhide** [comment]
Well, it's a difficult question to answer because sparsehash has been floating around for so long in various packages around the ecosystem (lunixbrew is a new one to me!), it's kind of hard to know what will or won't break if the autoconf is adjusted...

In an ideal world, the build system (cmake?) for the C+11 version would be improved and then we'd move that version into the release of this repository.

In the short term, if you have a patch which makes the tests pass and works without changing the autoconf stuff, make a pull request and reference this issue :-)
